In [1]:
import pandas as pd

In [16]:
df_1 = pd.read_csv("../data/raw/202501-divvy-tripdata.csv")

In [6]:
df_1.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member

In [8]:
df_1.shape

(138689, 13)

In [7]:
df_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 138689 entries, 0 to 138688
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             138689 non-null  str
 1   rideable_type       138689 non-null  str
 2   started_at          138689 non-null  str
 3   ended_at            138689 non-null  str
 4   start_station_name  115837 non-null  str
 5   start_station_id    115837 non-null  str
 6   end_station_name    114616 non-null  str
 7   end_station_id      114616 non-null  str
 8   start_lat           138689 non-null  float64
 9   start_lng           138689 non-null  float64
 10  end_lat             138628 non-null  float64
 11  end_lng             138628 non-null  float64
 12  member_casual       138689 non-null  str
dtypes: float64(4), str(9)
memory usage: 13.8 MB

In [11]:
df_1["rideable_type"].unique()

<StringArray>
['classic_bike', 'electric_bike']
Length: 2, dtype: str

In [12]:
df_1["member_casual"].unique()

<StringArray>
['member', 'casual']
Length: 2, dtype: str

In [13]:
df_2 = pd.read_csv("../data/raw/202502-divvy-tripdata.csv")

In [14]:
df_2.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,A246CA24873F7C5C,classic_bike,2025-02-25 21:21:21.171,2025-02-25 21:30:09.941,Michigan Ave & Lake St,TA1305000011,Clark St & Elm St,TA1307000039,41.886022,-87.624398,41.902973,-87.631280,member
1,303C0906F3F068AE,classic_bike,2025-02-08 14:55:13.493,2025-02-08 15:13:39.890,Ogden Ave & Race Ave,13194,Clark St & Elm St,TA1307000039,41.891795,-87.658751,41.902973,-87.631280,member
2,A0F65F3531F1FB2B,electric_bike,2025-02-24 00:32:56.553,2025-02-24 00:38:21.711,Michigan Ave & Lake St,TA1305000011,Wabash Ave & 9th St,TA1309000010,41.886022,-87.624398,41.870769,-87.625734,casual
3,CE663C815B6A6D73,electric_bike,2025-02-07 17:00:38.646,2025-02-07 17:34:29.012,Ogden Ave & Race Ave,13194,Clark St & Elm St,TA1307000039,41.891795,-87.658751,41.902973,-87.631280,casual
4,43F626BEF919D026,classic_bike,2025-02-10 14:56:56.565,2025-02-10 15:01:18.745,Clark St & North Ave,13128,Clark St & Elm St,TA1307000039,41.911974,-87.631942,41.902973,-87.631280,member

In [15]:
df_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 151880 entries, 0 to 151879
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             151880 non-null  str
 1   rideable_type       151880 non-null  str
 2   started_at          151880 non-null  str
 3   ended_at            151880 non-null  str
 4   start_station_name  125952 non-null  str
 5   start_station_id    125952 non-null  str
 6   end_station_name    124631 non-null  str
 7   end_station_id      124631 non-null  str
 8   start_lat           151880 non-null  float64
 9   start_lng           151880 non-null  float64
 10  end_lat             151823 non-null  float64
 11  end_lng             151823 non-null  float64
 12  member_casual       151880 non-null  str
dtypes: float64(4), str(9)
memory usage: 15.1 MB