In [20]:
import pandas as pd

df = pd.read_csv("../data/raw/202501-divvy-tripdata.csv", parse_dates= ['started_at', 'ended_at'])

In [21]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member

In [22]:
df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str')

In [23]:
colums_to_remove = ['start_lat', 'start_lng', 'end_lat', 'end_lng']
df = df.drop(columns = colums_to_remove)

In [24]:
df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'member_casual'],
      dtype='str')

In [25]:
df["duration"] = df['ended_at'] - df['started_at']

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 138689 entries, 0 to 138688
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             138689 non-null  str
 1   rideable_type       138689 non-null  str
 2   started_at          138689 non-null  datetime64[us]
 3   ended_at            138689 non-null  datetime64[us]
 4   start_station_name  115837 non-null  str
 5   start_station_id    115837 non-null  str
 6   end_station_name    114616 non-null  str
 7   end_station_id      114616 non-null  str
 8   member_casual       138689 non-null  str
 9   duration            138689 non-null  timedelta64[us]
dtypes: datetime64[us](2), str(7), timedelta64[us](1)
memory usage: 10.6 MB

In [27]:
has_negative = (df["duration"] < pd.Timedelta(0)).any()
has_zero = (df["duration"] == pd.Timedelta(0)).any()
print(has_negative, has_zero)

False False

In [28]:
df["duration_seconds"] = df["duration"].dt.total_seconds().astype(int)
df.drop(columns = ["duration"])

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,duration_seconds
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,member,837
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,member,304
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,member,695
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,member,214
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,member,154
...,...,...,...,...,...,...,...,...,...,...
138684,EDA9D2E5E9522300,classic_bike,2025-01-12 14:16:33.861,2025-01-12 14:24:16.135,Ellis Ave & 60th St,KA1503000014,Ellis Ave & 53rd St,KA1503000052,member,462
138685,00B2ACA37BFEE6CD,electric_bike,2025-01-18 09:44:57.802,2025-01-18 09:50:34.544,Ellis Ave & 60th St,KA1503000014,Ellis Ave & 53rd St,KA1503000052,member,336
138686,42B036EAD9E813FB,classic_bike,2025-01-06 08:03:09.104,2025-01-06 08:08:16.801,Wells St & Walton St,TA1306000011,Wells St & Hubbard St,TA1307000151,member,307
138687,870C92298391825D,classic_bike,2025-01-09 15:28:02.640,2025-01-09 15:35:22.135,Ellis Ave & 60th St,KA1503000014,Ellis Ave & 53rd St,KA1503000052,casual,439
138688,3D0D009614056F36,classic_bike,2025-01-08 07:56:05.205,2025-01-08 08:01:07.372,Wells St & Walton St,TA1306000011,Wells St & Hubbard St,TA1307000151,casual,302

In [29]:
df.iloc[0, 2]

Timestamp('2025-01-21 17:23:54.538000')

In [30]:
df["trip_date"] = df["started_at"].dt.normalize()
df["trip_year"] = df["started_at"].dt.year
df["trip_month"] = df["started_at"].dt.month
df["trip_weekday"] = df["started_at"].dt.day_name()
df["trip_hour"] = df["started_at"].dt.hour

In [31]:
df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'member_casual', 'duration', 'duration_seconds',
       'trip_date', 'trip_year', 'trip_month', 'trip_weekday', 'trip_hour'],
      dtype='str')

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 138689 entries, 0 to 138688
Data columns (total 16 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             138689 non-null  str
 1   rideable_type       138689 non-null  str
 2   started_at          138689 non-null  datetime64[us]
 3   ended_at            138689 non-null  datetime64[us]
 4   start_station_name  115837 non-null  str
 5   start_station_id    115837 non-null  str
 6   end_station_name    114616 non-null  str
 7   end_station_id      114616 non-null  str
 8   member_casual       138689 non-null  str
 9   duration            138689 non-null  timedelta64[us]
 10  duration_seconds    138689 non-null  int64
 11  trip_date           138689 non-null  datetime64[us]
 12  trip_year           138689 non-null  int32
 13  trip_month          138689 non-null  int32
 14  trip_weekday        138689 non-null  str
 15  trip_hour           138689 non-null  int32
dtypes: datetime64[us](3), int32(3), int64(1), str(8), timedelta64[us](1)
memory usage: 15.3 MB

In [33]:
df["trip_year"].unique()

array([2025, 2024], dtype=int32)

In [34]:
(df.loc[df["trip_year"] == 2024]).head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,duration,duration_seconds,trip_date,trip_year,trip_month,trip_weekday,trip_hour
10,3C1E48C025E88653,classic_bike,2024-12-31 23:52:33.890,2025-01-01 00:23:51.880,DuSable Lake Shore Dr & Wellington Ave,TA1307000041,Broadway & Barry Ave,13137,member,0 days 00:31:17.990000,1877,2024-12-31,2024,12,Tuesday,23
2194,30492B570C669826,electric_bike,2024-12-31 23:56:42.586,2025-01-01 00:20:06.614,Wabash Ave & Grand Ave,TA1307000117,Spaulding Ave & Division St,15654,casual,0 days 00:23:24.028000,1404,2024-12-31,2024,12,Tuesday,23
4674,E68088DE9EEB134D,electric_bike,2024-12-31 23:48:11.256,2025-01-01 00:04:41.770,Wabash Ave & Roosevelt Rd,TA1305000002,DuSable Lake Shore Dr & Monroe St,13300,casual,0 days 00:16:30.514000,990,2024-12-31,2024,12,Tuesday,23
4675,5685D9F19016E133,electric_bike,2024-12-31 23:47:09.958,2025-01-01 00:04:37.797,Wabash Ave & Roosevelt Rd,TA1305000002,DuSable Lake Shore Dr & Monroe St,13300,casual,0 days 00:17:27.839000,1047,2024-12-31,2024,12,Tuesday,23
4681,9D029A0F2E00CFE5,classic_bike,2024-12-31 23:39:08.304,2025-01-01 00:30:27.268,Emerald Ave & 31st St,TA1309000055,Loomis St & Archer Ave,KA1503000040,member,0 days 00:51:18.964000,3078,2024-12-31,2024,12,Tuesday,23

In [35]:
df["trip_month"].unique()

array([ 1, 12], dtype=int32)

In [36]:
df["trip_weekday"].unique()

<StringArray>
['Tuesday', 'Saturday', 'Thursday', 'Sunday', 'Friday', 'Monday', 'Wednesday']
Length: 7, dtype: str

In [37]:
df["trip_hour"].unique()

array([17, 15,  8, 16,  1,  6, 23, 18, 12, 13,  9, 11,  7, 10, 22,  0, 21,
       19, 14, 20,  5,  3,  2,  4], dtype=int32)

In [38]:
df.to_csv('../data/processed/trips_clean202501.csv', index=False)